Numpy Assignments

In [25]:
# case study problems

In [2]:
# Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a
# Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return
# [
# [5, 5, 5],
# [5, 5, 5],
# [5, 5, 5]
# ]


In [13]:
# importing numpy 

In [3]:
import numpy as np

In [10]:
a=[[5, 5,5] ,[5,5,5],[5,5,5]]

In [11]:
a

[[5, 5, 5], [5, 5, 5], [5, 5, 5]]

In [ ]:
# Another method

In [33]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [12]:
# . Create a method that takes n Numpy arrays of same dimensions sums them and return the
# answer.

In [23]:
lst = []
num = int(input("Enter the size of the array: "))
print("Enter array elements: ")
for n in range(num):
  numbers = int(input())
  lst.append(numbers)
print("Sum:", sum(lst))

Enter the size of the array: 10
Enter array elements: 
1
2
2
3
4
5
6
7
8
9
Sum: 47


In [24]:
# Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two
# numbers N and M. The method should return the top-left N X M sub matrix e.g:
# [
# [1, 2, 3],
# [4, 5, 6],
# [7, 8, 9],
# ]
# top_left_sub_matrix (matrix, 2, 2) -> should return:
# [
# [1, 2]
# [4, 5]
# ]

In [52]:
c=np.arange(1,10).reshape(3,3)
print(c,"n\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]] n



In [62]:
c[0:2,:2]

array([[1, 2],
       [4, 5]])

In [63]:
#. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two
# numbers N and M The method should return the bottom-right N X M sub matrix e.g.:
# [
# [1, 2, 3],
# [4, 5, 6],
# [7, 8, 9],
# ]
# sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
# [
# [5, 6]
# [8, 9]
# ]

In [88]:
c[1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
# . Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method
# should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's
# standard deviation as values:
# [1, 1, 1]
# solution(arr) -> should return :
# {'mean': 1.0, 'std_dev': 0.0

In [4]:
import numpy as np
d=[1,1,1]
np.std(d)

0.0

In [6]:
###############

In [5]:
# Data structure Assignment

In [37]:
# >>>>>>

In [7]:
# 1. Create a list named ‘myList’ that is having the following elements: 10,20,30,’apple’, True, 8.10.
# a. Now in the ‘myList’, append these values: 30,40
# b. After that reverse the elements of the ‘myList’ and store that in ‘reversedList’

In [20]:
mylist=[10,20,30,'apple',True,8.10]

In [21]:
mylist

[10, 20, 30, 'apple', True, 8.1]

In [22]:
mylist.append(30)

In [23]:
mylist

[10, 20, 30, 'apple', True, 8.1, 30]

In [24]:
mylist.append(40)

In [25]:
mylist

[10, 20, 30, 'apple', True, 8.1, 30, 40]

In [32]:
reverselist=mylist.pop()

In [33]:
reverselist

40

In [34]:
reverselist=mylist.pop()

In [35]:
reverselist

30

In [36]:
# 2. Create a dictonary with key values as 1,2,3 and the values as ‘data’,’information’, and ‘text’.
#    a. After that eliminate the ‘text’ value form the dictonary.
#    b. Add ‘features’ in the dictonary.
#    c. Fetch the ‘data’ element from the dictonary and display it in the output.

In [39]:
product_list=[[1,"data"],[2,"information"],[3,"text"]]
product_list=dict(product_list)
product_list

{1: 'data', 2: 'information', 3: 'text'}

In [40]:
# 3. Create a tuple and add these elements 1,2,3,apple,mango in ‘my_tuple

In [41]:
friend_tuple=("Ram","sam")

In [78]:
friend_tuple=("Ram","sam")
p_tuple=(1,2,3,"apple","mango")
my_tuple=friend_tuple+p_tuple

In [79]:
my_tuple

('Ram', 'sam', 1, 2, 3, 'apple', 'mango')

In [49]:
# 4. Create another tuple named numeric_tuple consisting of only integer values 10,20,30,40,50
#    a. Find the minimum value from the numeric_tuple.
#    b. Concatenate my_tuple with numeric_tuple and store the result in r1.
#    c. Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’.


In [50]:
numeric_tuple=(10,20,30,40,50)


In [72]:
min(numeric_tuple)


10

In [53]:
my_tuple=(7,8,9)

In [80]:
r1=numeric_tuple+my_tuple

In [81]:
r1

(10, 20, 30, 40, 50, 'Ram', 'sam', 1, 2, 3, 'apple', 'mango')

In [82]:
# Duplicate of a tuple

In [83]:
my_tuple=(7,8,9)*2

In [84]:
my_tuple

(7, 8, 9, 7, 8, 9)

In [85]:
my_tuple=(7,)*5
my_tuple

(7, 7, 7, 7, 7)

In [86]:
# 5. Create 2 sets with name set1 and set2, where set1 contains{1,2,3,4,5} and set2 to
#     contains{2,3,7,6,1}
#    a. Perform the below operation:
#     a. set1 union set2
#     b. set1 intersection set2
#     c. set1 difference set2

In [90]:
set1={1,2,3,4,5}
set2={2,3,7,6,1}
set1.union(set2)


{1, 2, 3, 4, 5, 6, 7}

In [91]:
set1.intersection(set2)

{1, 2, 3}

In [92]:
set1.difference(set2)

{4, 5}

In [93]:
###########################################################################

In [94]:
# Numpy Assignments

In [95]:
# 1. Create a 3x3 matrix array with values ranging from 2 to 10.

In [108]:
import numpy as np
a=np.arange(2,11).reshape(3,3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [109]:
#2. Create a numpy array having user input values and convert the integer type to the float type
#   of the elements of the array. For instance:
#   Original array
#   [1, 2, 3, 4]
#   Array converted to a float type:
#   [ 1. 2. 3. 4.]

In [117]:
a=[1,2,3,4]
for i in a :
    a=float(i)
    print(a)

1.0
2.0
3.0
4.0


In [118]:
#3. Write a Numpy program to append values to the end of an array. For instance:
#   Original array:
#   [10, 20, 30]
#   After append values to the end of the array:
#   [10 20 30 40 50 60 70 80 90]

In [121]:
a=[10,20,30]
b=[40,50,60,70,80,90]
for i in b:
    a.append(i)
    print(a)

[10, 20, 30, 40]
[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50, 60]
[10, 20, 30, 40, 50, 60, 70]
[10, 20, 30, 40, 50, 60, 70, 80]
[10, 20, 30, 40, 50, 60, 70, 80, 90]


In [123]:
# 4. Create two numpy arrays and add the elements of both the arrays and store the result in
#    sumArray.


In [126]:
import numpy as np
array1=np.array([1,2,3])
array2=np.array([4,5,6])
np.add(array1,array2)
print(np.add(array1,array2))

[5 7 9]


In [127]:
#5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform
#   the following tasks:
#     a. Extract the 1st row from the array.
#     b. Extract the last element from the array.

In [146]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print(a)
    

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [148]:
a[0:1]

array([[10, 20, 30]])

In [167]:
a[2,2]

90